In [1]:
import numpy as np

In [3]:
x = [8, 9, 10, 11]
y = [12, 13, 14, 15]
z = np.add(x, y) #1

print(z)

[20 22 24 26]


In [4]:
def testaddition(a, b):
  return a+b

myadd = np.frompyfunc(testaddition, 2, 1) #2

print(myadd([9,10, 11, 12], [13, 14, 15, 6]))

[22 24 26 18]


In [5]:
print(type(np.add)) #3


<class 'numpy.ufunc'>


In [6]:
ar1 = np.array([100, 200, 300, 400, 500, 600])
ar2 = np.array([200, 210, 220, 230, 240, 250])

ar3 = np.subtract(ar1, ar2) #4

print(ar3)

[-100  -10   80  170  260  350]


In [7]:
ar4 = np.multiply(ar1, ar2)
print(ar4)

[ 20000  42000  66000  92000 120000 150000]


In [8]:
ar5 = np.divide(ar1, ar2) #5
print(ar5)

[0.5        0.95238095 1.36363636 1.73913043 2.08333333 2.4       ]


In [10]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
ar6 = np.power(arr1, arr2) #6
print(ar6)

[      1000    3200000  729000000 -520093696       2500          0]


In [12]:
ar7 = np.mod(arr1, arr2) #7
print(ar7)

[ 1  0  0  0  0 27]


In [13]:
ar8 = np.remainder(arr1, arr2) #8
print(ar8)

[ 1  0  0  0  0 27]


In [14]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr) #9

print(newarr)

[1 2 1 2 3 4]


In [15]:
arr = np.around(3.1666, 2) # 10

print(arr)

3.17


In [16]:
arr = np.floor([-3.1666, 3.6667]) # 11

print(arr)


[-4.  3.]


In [17]:
arr = np.ceil([-3.1666, 3.6667]) # 12

print(arr)

[-3.  4.]


In [18]:
arr = np.array([1, 2, 3]) # 13

newarr = np.cumsum(arr)

print(newarr)


[1 3 6]


In [19]:
arr = np.array([1, 2, 3, 4]) #14

x = np.prod(arr)

print(x)

24


In [20]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2]) # 15

print(x)

40320


In [21]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1) # 16

print(newarr)

[  24 1680]


In [22]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr) # 17

print(newarr)

[  5  10 -20]


In [23]:
arr = np.array([1, -1, 0.1])

x = np.arcsin(arr) # 18

print(x)


[ 1.57079633 -1.57079633  0.10016742]


In [25]:
base = 3
perp = 4

x = np.hypot(base, perp) # 19

print(x)

5.0


In [26]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2) # 20

print(x)

12
